--- 
arch: 
  packages: 
    - procps-ng
    - reflector
    - screenfetch-git
  repos: 
    - "archlinuxfr=http://repo.archlinux.fr/$arch"
  script: 
    - "sudo screenfetch"
    - "reflector --verbose -l 20 --sort rate -p https"
    - "echo $CC"
    - "touch test_file"
compiler: 
  - gcc
  - clang
language: c
script: 
  - make
  - "make test"

